services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "2015:2015"
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.docker/caddy/data:/data