FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm install -g tsx 

COPY .env ./

ENTRYPOINT ["sh", "-c", "npx tsx ./src/RSScli/index.ts \"$@\"", "sh"]