name: tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: check
        uses: actions/checkout@v4
      
      - name: node
        uses: actions/setup-node@v4
        with: 
          node-version: 22
      
      - name: install
        run: npm ci

      - name: Add logging file
        run: touch logs/log.txt
        
      - name: Run tests
        run: npm run test